apiVersion: v1
kind: Service
metadata:
  name: glue_connection
spec:
  selector:
    app: glue_connection
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
